### ISSUE TITLE
Move `unifiedjs/governance` to `unifiedjs/collective`

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/collective#30]
Hi folks! 👋

I’d like to move this project, `unifiedjs/governance`, to `unifiedjs/collective`.
The reasoning is that this would allow `unifiedjs/governance` to be used for the organization team, whereas `unifiedjs/collective` would be used by the @unifiedjs/core team.
This would allow all organisation teams to have their own `governance` repository to talk about the things they govern, and give the collective team their own place.

A different issue is that I’d like a `unifiedjs/moderation` project to exist, governed by the moderation team, I’ll leave that up to @unifiedjs/moderators.

Per GH-29, renaming a project is intentionally undefined, therefore there is no motion, vote, or playbook involved. But I’d like to ask for opinions / feedback anyway!

/cc @unifiedjs/core

**Comment by ChristianMurphy** [comment]
@wooorm what (if anything) would be left in the governance repo?

**Comment by wooorm** [comment]
To clarify:

* I think org teams need to specify how they maintain and manage code, whereas the core team should be administrative.
* I think all organisations should have a repo with a single name, `governance`, to document their governance (stuff that’s more practical than what the collective should dictate).
* I think that collective teams (core, moderation) also need a place to define policy.
* As `unifiedjs` (the org) needs a place to discuss, and `governance` is a good name for the governance of an org, I think `governance` should be used by orgs, and `core` should move to another place.

**Comment by wooorm** [comment]
What those governance repos hold is up for debate and, I think, will be figured out while implementing them.

But I’m thinking something like the readme of a [`.github` repo](https://github.com/unifiedjs/.github), except for all the other files, instead linking to the collective policies.

**Comment by ChristianMurphy** [comment]
A few more follow up questions:
1. Is the intent that there will be one `collective` repo for all orgs? or one per org?
2. Is the name `collective` related to core team will be using opencollective?
3. Why do core and non-core teams need different policies? Aren't they both part of the same org?
4. Would https://help.github.com/en/articles/about-team-discussions help for creating rooms where teams can discuss internally?

**Comment by wooorm** [comment]
> Is the intent that there will be one collective repo for all orgs? or one per org?

The intent is that collective teams needs a place. It makes sense for that place to be in `unifiedjs` but it could be in a new org as well. I envision one `unifiedjs/collective` org (and `npm-tools` plus `github-tools) to be managed by the core collective team, and one `unifiedjs/moderation` org to be 
managed by the moderation collective team.

> Is the name collective related to core team will be using opencollective?

The term collective is for the group of organizations, a “collective” of organisations. Unrelated to OC.

> Why do core and non-core teams need different policies? Aren't they both part of the same org?

The collective needs a policy, so that it doesn’t need to be places in all the organizations. The collective can define high-level policies, whereas organizations can deviate and define more practical policies.

> Would https://help.github.com/en/articles/about-team-discussions help for creating rooms where teams can discuss internally?

Not really, as those are private. I’d prefer communication to happen in public. Additionally, that only gives a place for GH teams on org teams. The collective teams will have 9 places to discuss.

**Comment by ChristianMurphy** [comment]
Okay, that makes more sense.
Seems like a good plan.

**Comment by Murderlon** [comment]
Changing the name to `unifiedjs/collective` makes sense to me for the current set of policies and their intent. I also do like the idea of org scoped practicalities, provided that it doesn't become unnecessary micro-management. Perhaps it could be the place for agreed upon config files (such as `.editorconfig`, `.prettierrc`, etc) that every project should start with. In any case, we don't have to figure that out now for this name change.

**Comment by RichardLitt** [comment]
This sounds fine to me. However, I worry that this is a lot of bike-shedding; I don't know how important this is to making Unified run well, in general.

**Comment by wooorm** [comment]
@RichardLitt There are a few ideas floating around here, could you expand on what feels okay and what’s maybe too much? (this repo name change, 9 `governance` repos, documenting how orgs practically handle their own business, a home for moderation)?

My plan is to:
1. Change this name to `unifiedjs/collective`
2. Create 9 `governance` repos for the other orgs, similar too `.github`, but only a readme linking to `unifiedjs/collective` policies. Very minimal for now

I think this will empower orgs/teams as it gives them more of a sense of ownership, through having their own space, and allowing them to deviate. I want to leave how that looks up to orgs.

To explain my motivation, I hope this allows a shift from centralised (current) to more federated (future). I think that’s a good thing (though that’s subjective). And even more meta: I don’t want to be BDFL

**Comment by wooorm** [comment]
Moved, thanks for the discussion folks!
As this thread includes other thoughts for future changes, feel free to continue discussing those.

**Comment by RichardLitt** [comment]
Thanks, @wooorm. 

> To explain my motivation, I hope this allows a shift from centralised (current) to more federated (future). I think that’s a good thing (though that’s subjective). And even more meta: I don’t want to be BDFL

If this is towards that end, then let's do it, for sure. :) 

(No worries that, of course, this was already done. I didn't have the time previously to get to this.)

**Comment by wooorm** [comment]
Perfect!
And don’t worry about that, it’s still valued after the merge. I’m pretty compulsive about closing open things, especially such as this, as it’s reversible. So if anyone in the future doesn’t agree with a made commit or merged PR, it can be reversed!
