### ISSUE TITLE
GitHub sponsors

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/collective#38]
Hi folks! I wanted to discuss whether it makes sense for us to include GitHub Sponsors references in `funding.yml` files, next to our OC reference.

Currently with only OC:

<img width="470" alt="Screenshot 2019-10-22 at 9 52 38 am" src="https://user-images.githubusercontent.com/944406/67266989-b8e64c00-f4b1-11e9-8d67-6d1c791062a2.png">

OC with GHS (example from Babel):

<img width="479" alt="Screenshot 2019-10-22 at 9 53 27 am" src="https://user-images.githubusercontent.com/944406/67267035-cef40c80-f4b1-11e9-8afe-b00423b5af52.png">

The reason for discussing this is that I got into the GHS beta (and they’re gearing up to allow anyone to join).

I haven’t mentioned that I got into the beta because I like OC a lot:

- OC is transparent
- OC is about a group of people, not about ego (which really fits with what unified is doing)
- I can quit/be expelled and unified remains

But there are reasons to think about GHS:

- Money is tight, so if people want to sponsor, why not let them 🤷‍♂️
- GH doubles money for now (from the day you join, to exactly a year later)
- GHS is (currently) person to person, which is different from OC, so adding GHS may not mean OC decreases?

What are your thoughts?

**Comment by BarryThePenguin** [comment]
> GH doubles money for now (from the day you join, to exactly a year later)

This makes a lot of financial sense 💯 

> GHS is (currently) person to person, which is different from OC, so adding GHS may not mean OC decreases?

That's the main risk I see. Would it distract potential sponsors from contributing to the individual over the collective?

Maybe that is only a problem if there were more contributors who were receiving funding? If that were the case, that could enable the individual contributors to give back the collective?

I think this is a reasonable idea 👍

**Comment by Murderlon** [comment]
Seems like a great idea. I also don't think this will draw away money from OC, it just gives people more options. Maybe they're more touched by your GHS bio than unified's OC and decide to sponsor you while they're there. Besides, people added to the sponsors there are mostly maintaining unified, but also do other things. So no need for guilt if it would draw away a tiny bit from OC.

**Comment by ChristianMurphy** [comment]
Would it make sense to leverage GitHub sponsors for the project as a whole https://github.blog/2019-11-13-universe-day-one/#sponsors ?
Rather than a list of individual contributors?

**Comment by wooorm** [comment]
Needs a credit card / company apparently 🤔

**Comment by ChristianMurphy** [comment]
Sounds similar to the requirement from OC on https://docs.opencollective.com/help/collectives/add-or-change-fiscal-host

**Comment by wooorm** [comment]
That's a service provided by OC. GH requires you to run your own company

**Comment by wooorm** [comment]
Our fiscal host on the open collective platform is the open source collective, which charges a small amount of money to file all our taxes. Github seems to require you to run your own, and be liable, which is not very ideal

**Comment by ChristianMurphy** [comment]
A statement from open collective, in their latest platform update email:

> ### Github
>
> A new feature enables funding directly through a Sponsor button on project repos and payment through Github to your Collective. To activate it, you need an entity and a bank account for your project—luckily, we already provide that as your fiscal sponsor! We're working with Github to offer Collectives early access to this invite-only feature.

**Comment by RichardLitt** [comment]
> Our fiscal host on the open collective platform is the open source collective, which charges a small amount of money to file all our taxes. Github seems to require you to run your own, and be liable, which is not very ideal

How easy is this to set up in the Netherlands?

**Comment by wooorm** [comment]
From what I’ve heard from GH (devon, in the original private repo of people in the sponsors program), is that they don’t give advice on tax: you have to deal with this yourself. OC is similar, they don‘t provide tax help, but they do say: we do everything on the sponsor side, you just bill to our (US, in our case) company, as if you are a freelancer.

Tax is different per country. For Europe it essentially means that, for any sponsor on GH, I need to figure out where they are from, and give a certain amount of the money I got from that person to that country’s authorities. 😓

**Comment by wooorm** [comment]
I’ve gotten us on the waiting list for GH sponsors x OC, as announced and described here: https://twitter.com/opencollect/status/1228372194281033728

Btw, @timneutkens, your private non-work email is noted as the billing address for the MDX org, and therefore is on file for GH sponsors. Should we change that to John’s or my email?

**Comment by RichardLitt** [comment]
Great move, @wooorm!

**Comment by wooorm** [comment]
…and we’re accepted already! Started filling out the details (this’ll take more time) but because I already have a Stripe account for personal GH sponsors, GH now connected that to the first org I tried, instead of letting me set up an OC connection 🙄

Anyway, I’m in contact with people working on this but it’s the weekend so will take a bit!

**Comment by timneutkens** [comment]
> Btw, @timneutkens, your private non-work email is noted as the billing address for the MDX org, and therefore is on file for GH sponsors. Should we change that to John’s or my email?

I honestly don't know why this is the case! Maybe because I created the org, definitely feel free to update! Can you dm me your email?

**Comment by wooorm** [comment]
@timneutkens changed it to my email and now I can set up GHS + OC for MDX as well!

**Comment by wooorm** [comment]
Alright we’ve been approved for all orgs (except remarkjs 🤔😓), thanks to @Murderlon setting up a stripe connect, and GH accepting us!

But: I missed that we can link all repos to the `unifiedjs` sponsors account in `funding.yml`, we don’t need separate sponsorships for all the other orgs! So a question for y’all: **should we a) go with separate sponsors page per org, b) go with a single sponsors for unifiedjs**?

- Upside of a) is that there will be a sponsors button on https://github.com/remarkjs (with b) it would only appear on repos)
- Upside of a) is that people may want to sponsor MDX but don’t know about unified
- Upside of a) is that orgs could in the future split off retaining their sponsors
- Upside of b) is that people will potentially contribute more if they’re sponsoring the whole
- Upside of b) is that there will be a single badge on people’s profile, and we’ll have higher counts of supporters on https://github.com/sponsors/unifiedjs

for example: [remarkjs is set up to sponsor unifiedjs](https://github.com/remarkjs), [rehypejs is set up with its own sponsors](https://github.com/rehypejs), haven’t set up the rest

**Comment by RichardLitt** [comment]
To your second point: if people want to sponsor mdx, won't they see that it's part of unified? Will it simply not show for mdx? 

I think b makes more sense.

**Comment by Murderlon** [comment]
I also feel b makes more sense.

**Comment by wooorm** [comment]
Alright, went with B, unpublished all sponsors dashboards except for unified, and linked all `.funding.yml`s to unified. Every project in the collective now shows GH like so when activating “sponsor”

<img width="536" alt="Screen Shot 2020-05-03 at 11 16 13 am" src="https://user-images.githubusercontent.com/944406/80910423-a174ff00-8d2f-11ea-9936-e6d2156e73b0.png">

Thanks folks!
