### ISSUE TITLE
Add `funding` fields to packages

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/collective#40]
npm recently added support for a `funding` field in `package.json`: https://github.com/npm/rfcs/blob/latest/accepted/0017-add-funding-support.md#implementation

```json
  "funding": {
    "type": "opencollective",
    "url": "https://opencollective.com/unified"
  },
```

This’ll standardise that field and I suspect other tools will join in as well.

**Comment by ChristianMurphy** [comment]
Could adding this field be automatically added the collective using github-tools or npm-tools?

**Comment by wooorm** [comment]
GH tools can’t push to repos or publish packages (the latter step is needed for funding to take effect.) Automatically publishing packages can also be dangerous because they may contain unreleased non-patch changes.

---

Node’s package maintenance project (which concerns itself with the ecosystem better), also recently added a new [`support` field in `package.json`](https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/PACKAGE-SUPPORT.md). It’s an interesting proposal, and for unified I drafted this example to try it out (it defines me as potential paid/contracting support option):

```js
"support": {
  "versions": [
    {
      "version": "^7.0.0", // (current major?)
      "target": {
        "node": "active"
      },
      "response": [
        {
          "type": "regular-7", // 7 days unpaid response time for free by volunteers
          "paid": false,
          "contact": {
            "name": "Volunteers",
            "url": "https://github.com/unifiedjs"
          }
        },
        {
          "type": "24-7", // 6 hours paid response time (could also do `regular-1`)
          "paid": true,
          "contact": [
            "Titus Wormer <tituswormer@gmail.com> (https://wooorm.com)"
          ]
        }
      ],
      "backing": {
        "sponsored": "https://opencollective.com/unifiedjs",
        "paid-support": "https://wooorm.com"
      }
    }
  ]
}
```

**Comment by ChristianMurphy** [comment]
> GH tools can’t push to repos or publish packages (the latter step is needed for funding to take effect.) Automatically publishing packages can also be dangerous because they may contain unreleased non-patch changes.

But it could add the field across hundreds of repos, so it will be there when the next release is cut.

**Comment by wooorm** [comment]
Yes, true! But there’s no code for changing Git repo’s yet, so that would take a significant amount of time. I image the work to do that is also a lot, because we have monorepos as well, and `package.json` files in test suites. So it’ll be hard to automate.
I estimate the manual work to be 24-32 hours, which has the benefit of walking through every repo, updating deps, fixing some issues, etc. Automating will cost at least 16 hours?

**Comment by johno** [comment]
I'd suggest updating the top ~25-50 packages as a start. I'd imagine there's quite a long tail of packages with less downloads. 🤷‍♂

**Comment by wooorm** [comment]
The highly starred and highly downloaded packages have funding fields now!

```
mdast-util-to-string@1.0.7, unist-util-remove-position@1.1.4, vfile-location@2.0.6, remark-parse@7.0.2, mdast-util-compact@1.0.4, remark-stringify@7.0.4, unist-util-stringify-position@2.0.2, vfile-message@2.0.2, vfile@4.0.2, unified@8.4.2, remark@11.0.2, remark-cli@7.0.1, unist-util-modify-children@1.1.5, retext-english@3.0.4, unist-util-generated@1.1.5, unist-util-position@3.0.4
├── type: opencollective
├── url: https://opencollective.com/unified
├─┬ glob@7.1.6
│ └── url: https://github.com/sponsors/isaacs
└─┬ es-to-primitive@1.2.1
  └── url: https://github.com/sponsors/ljharb
```
