### ISSUE TITLE
Nominating @laurieontech as a member of @mdx-js

### ISSUE THREAD

**Issue by johno** [unifiedjs/collective#41]
Laurie is a member of Gatsby's themes team and has a lot of experience with MDX's integration in Gatsby and will be helping us maintain MDX core.

**Comment by wooorm** [comment]
Hi @laurieontech! What npm username and email address shall I use for you (+ optionally a url to your website or such)?

**Comment by laurieontech** [comment]
Hey 👋🏻

npm is also laurieontech

site is https://laurieontech.dev

**Comment by wooorm** [comment]
You’re added! Welcome Laurie! 👋 Tooling will now invite you to orgs, and set you up with the correct permissions.

You are now a [merger](https://github.com/unifiedjs/collective/blob/master/permissions.md) on the whole @mdx-js organization.

Please take the time to read through the [collective governance repository](https://github.com/unifiedjs/collective) to find out what we expect from you, and what you can expect from us. You are welcome here, and to make sure other people are welcome as well, please adhere to our [code of conduct](https://github.com/unifiedjs/collective/blob/master/code-of-conduct.md).

@johno is lead of the MDX organization, and MDX is a bit different than the rest of the collective in some matters like code style, so please check in with John for MDX relating questions.
You are also free to ping other members, including me! But I try to keep a bit of a broader view of the whole collective (although these weeks I’m spending my time on improving MDX parsing).

**Comment by laurieontech** [comment]
Thanks so much! Excited to be on board!
