### ISSUE TITLE
Nominating @remcohaszing as a contributor of @remarkjs, @rehypejs, @syntax-tree

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/collective#42]
Remco has been adding to [types to @remarkjs, @rehypejs, @syntax-tree](https://github.com/search?p=1&q=author%3Aremcohaszing+org%3Aunifiedjs+org%3Avfile+org%3Asyntax-tree+org%3Aremarkjs+org%3Arehypejs+org%3Aretextjs+org%3Aredotjs+org%3Amicromark+org%3Amdx-js&type=Issues), participation that matches that of a contributor, but is (currently) not interested in becoming a maintainer.

See [Motion to nominate a contributor](https://github.com/unifiedjs/collective/blob/master/members.md#motion-to-nominate-a-contributor) for more information.

@unifiedjs/core Please vote

@remcohaszing Can I use your commit-associated email address? Do you have an npm username?

**Comment by remcohaszing** [comment]
Yes, you can use that email address. I’ll repeat it anyway for clarity.

**email**: remcohaszing@gmail.com
**npm username**: remcohaszing

**Comment by wooorm** [comment]
You’re added! Welcome Remco! 👋 Tooling will now invite you to orgs, and set you up with the correct permissions.

You are now a contributor on the whole @remarkjs, @rehypejs, and @syntax-tree organizations.

Please take the time to read through the collective governance repository (this one) to find out what we expect from you, and what you can expect from us. You are welcome here, and to make sure other people are welcome as well, please adhere to our code of conduct.

I’m the lead of the three aforementioned organizations, so feel free to direct questions towards me. Or ask other team members!
