### ISSUE TITLE
Bad links on npm - tracking only

### ISSUE THREAD

**Issue by tomByrer** [unifiedjs/collective#43]
I didn't test, but I imagine this affects ALL your npm packages

> Seems the hip thing to do is to change repos' primary branches from `master` to `main`.  But seems your [npm] pages don't reflect those changes, even if their package.json is updated:

https://www.npmjs.com/package/rehype-stringify

No action needed on your part; just posted here to help track.

https://twitter.com/ethomson/status/1281223587546963968

**Comment by wooorm** [comment]
It affects “monorepos”, some of which have been updated already, some haven’t.

See also: https://github.com/remarkjs/remark-lint/issues/239

**Comment by wooorm** [comment]
For folks reading along or stumbling on this in the future: GH now has some form of aliasing from master, when missing, to the default branch: https://github.com/github/renaming/
