### ISSUE TITLE
Motion to archive "ideas" repos and migrate them to GitHub discussions

### ISSUE THREAD

**Issue by ChristianMurphy** [unifiedjs/collective#44]
Unified has a number of "ideas" repos, this repos predate discussions and were/are designed for discussions which may be long lasting and don't really fit in the issue tracker of a repository.
It seems that GitHub discussions, with it's "idea" discussion type may better serve this purpose.
I purpose adding a comment to each "ideas" repo issue pointing it to discussions, closing the issues, and archiving the repositories.
The mapping from ideas to the respective discussions would be:
* https://github.com/unifiedjs/ideas -> https://github.com/unifiedjs/unified/discussions
* https://github.com/remarkjs/ideas -> https://github.com/remarkjs/remark/discussions
* https://github.com/rehypejs/ideas -> https://github.com/rehypejs/rehype/discussions
* https://github.com/retextjs/ideas -> https://github.com/retextjs/retext/discussions
* https://github.com/redotjs/ideas -> https://github.com/redotjs/redot/discussions
* https://github.com/syntax-tree/ideas -> ~??? (not sure with this one, open to suggestions)~ https://github.com/syntax-tree/unist/discussions

**Comment by wooorm** [comment]
Sounds good!

All the orgs have a main repo with discussions enabled. For syntax-tree that’s unist!

**Comment by ChristianMurphy** [comment]
Issues have a comment pointing to discussions, and repositories have been archived.
Sorry for any inconvenience caused, but having all the ideas and discussions unified in one place should make collaboration easier going forward.
Thanks all!
