### ISSUE TITLE
Nominating @remcohaszing as a contributor of @unifiedjs, @vfile

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/collective#51]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

See [Motion to nominate a contributor](https://github.com/unifiedjs/collective/blob/main/members.md#motion-to-nominate-a-contributor) for more information.

See [recent work](https://github.com/search?p=1&q=author%3Aremcohaszing+org%3Aunifiedjs+org%3Avfile+org%3Asyntax-tree+org%3Aremarkjs+org%3Arehypejs+org%3Aretextjs+org%3Aredotjs+org%3Amicromark+org%3Amdx-js&type=Issues)

### Solution

@unifiedjs/core Please vote (up/downvote this issue or leave a comment)

### Alternatives

n/a

**Comment by remcohaszing** [comment]
Contributor sounds great! Unless you believe maintainer is more fitting given my current activity.

**Comment by wooorm** [comment]
Done! for more info, see the info posted when you were first added to an org before here: https://github.com/unifiedjs/collective/issues/42#issuecomment-642580271.
If you want to become a maintainer, you can request that yourself.
See [¶ Participation](https://github.com/unifiedjs/collective/blob/main/members.md#participation) for what types of work is associated with different roles.
