### ISSUE TITLE
Nominating @JounQin as a maintainer of @micromark, @rehypejs, @remarkjs, @syntax-tree, @vfile, @unifiedjs

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/collective#57]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

See [Motion to nominate a maintainer](https://github.com/unifiedjs/collective/blob/main/members.md#motion-to-nominate-a-maintainer) for more information.

See [recent work](https://github.com/search?q=author%3AJounQin+org%3Aunifiedjs+org%3Avfile+org%3Asyntax-tree+org%3Aremarkjs+org%3Arehypejs+org%3Aretextjs+org%3Aredotjs+org%3Amicromark+org%3Amdx-js&type=Issues)

See request: https://github.com/orgs/unifiedjs/discussions/193#discussioncomment-3310133.

### Solution

@unifiedjs/core Please vote (up/downvote this issue or leave a comment)

### Alternatives

n/a

**Comment by JounQin** [comment]
I just realized that I want to be a releaser of `eslint-mdx`/`vscode-mdx`, etc. Should I post a new nomination for myself afterwards or it can just be included here?

**Comment by JounQin** [comment]
cc @wooorm

**Comment by wooorm** [comment]
Added. Within the next 24 hours, tooling will add you with the correct permissions to each of the above orgs.

On releasing, see: https://github.com/unifiedjs/collective/blob/main/members.md#request-to-become-a-releaser.

Note that releasers **have a lot of rights**. On GitHub. On npm. (See: https://github.com/unifiedjs/collective/blob/main/permissions.md). This group should remain small. I am not sure it is a good idea.

**Comment by JounQin** [comment]
OK then, let's just keep it as-is.

**Comment by wooorm** [comment]
> the releasers to more specific organizations 

Releasers are per organization already!

> or even repositories/packages?

That would help you, with `eslint-mdx`. True. A couple of other people also request similar things.
In my experience, typically, those people aren’t very active for very long. You’re an exception here!

With 500+ repos, it is very hard to get security right. I strongly believe that the best way to manage security, is **as few people and tools as possible that have access**.

Over the years, many tools we have used have had security problems: Coveralls for example. GitHub a couple of times. These services and many more leaked tokens.
This didn’t affect really us, **because we don’t give tools publish access**.

Having different people with different access per repo makes it hard to understand who does what: who has credentials? Who is responsible?

---

I also hope that working on orgs instead of repos brings a different level of commitment: that maintainers care for the whole group of things rather than one project.
I’d love to have more people on different organizations, solving issues, fixing PRs, cutting releases!
